### ISSUE TITLE
Docs on HTML support?

### ISSUE THREAD

**Issue by brettz9** [JonasKruckenberg/rollup-plugin-sri#2]
Hi,

Thanks for what looks like an incredibly useful plugin!

I assume someone has to use something like `@rollup/plugin-html`, as I see no docs on Rollup itself that indicate it can process HTML on its own. I'd think that should be really helpful to include in the example (and explain as needed). Thanks!

**Comment by JonasKruckenberg** [comment]
Hey! 
Thanks for the request, I made this plugin for my website not really expecting it to be used by people,
But if you’re interested I’ll add a bit more documentation and polish the whole thing a bit more! Stay tuned

**Comment by JonasKruckenberg** [comment]
If you think anything is missing please reopen or create a new issue
